# Basic Python

## 1. Split this string

In [9]:
s = "Hi there Sam!"

In [10]:
print(s.split())

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [14]:
planet = "Earth"
diameter = 12742

In [16]:
#a="The diameter of {.1f} is {diameter} kilometers" 
#print(a)
a = "The diameter of {0} is {1} kilometers".format(planet,diameter)
print(a)

The diameter of Earth is 12742 kilometers

## 3. In this nest dictionary grab the word "hello"

In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
print(d[1:3])

TypeError: unhashable type: 'slice'

# Numpy

In [4]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

## 5. Create an array of all the even integers from 20 to 35

## 6. Create a 3x3 matrix with values ranging from 0 to 8

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]